export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DISPATCH_CONFLICT: "DISPATCH_CONFLICT",
  CREW_CAPACITY_FULL: "CREW_CAPACITY_FULL",
  SKILL_MISMATCH: "SKILL_MISMATCH",
  SPARE_PART_MISSING: "SPARE_PART_MISSING",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  TICKET_NOT_DISPATCHABLE: "TICKET_NOT_DISPATCHABLE",
  OCCUPANCY_NOT_FOUND: "OCCUPANCY_NOT_FOUND",
  CALLBACK_INVALID: "CALLBACK_INVALID",
  QUEUE_ENTRY_NOT_FOUND: "QUEUE_ENTRY_NOT_FOUND",
  RECONCILIATION_NOT_FOUND: "RECONCILIATION_NOT_FOUND"
} as const;
