export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  TICKET_HELD: "TICKET_HELD",
  TICKET_NOT_HOLDABLE: "TICKET_NOT_HOLDABLE",
  HOLD_REQUIRED: "HOLD_REQUIRED",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  SKILL_MISMATCH: "SKILL_MISMATCH",
  CREW_CAPACITY_FULL: "CREW_CAPACITY_FULL",
  PART_SHORTAGE: "PART_SHORTAGE",
  ALREADY_QUEUED: "ALREADY_QUEUED",
  QUEUE_ENTRY_NOT_FOUND: "QUEUE_ENTRY_NOT_FOUND",
  TICKET_NOT_ACTIVE: "TICKET_NOT_ACTIVE",
  RECONCILIATION_NOT_FOUND: "RECONCILIATION_NOT_FOUND"
} as const;
export type ErrorCode = keyof typeof ERROR_CODES;
